// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/concourse/blackbox/syslog"
	"github.com/papertrail/remote_syslog2/syslog"
)

type FakeDrainer struct {
	DrainStub        func(line string, tag string) error
	drainMutex       sync.RWMutex
	drainArgsForCall []struct {
		line string
		tag  string
	}
	drainReturns struct {
		result1 error
	}
}

func (fake *FakeDrainer) Drain(line string, tag string) error {
	fake.drainMutex.Lock()
	fake.drainArgsForCall = append(fake.drainArgsForCall, struct {
		line string
		tag  string
	}{line, tag})
	fake.drainMutex.Unlock()
	if fake.DrainStub != nil {
		return fake.DrainStub(line, tag)
	} else {
		return fake.drainReturns.result1
	}
}

func (fake *FakeDrainer) DrainCallCount() int {
	fake.drainMutex.RLock()
	defer fake.drainMutex.RUnlock()
	return len(fake.drainArgsForCall)
}

func (fake *FakeDrainer) DrainArgsForCall(i int) (string, string) {
	fake.drainMutex.RLock()
	defer fake.drainMutex.RUnlock()
	return fake.drainArgsForCall[i].line, fake.drainArgsForCall[i].tag
}

func (fake *FakeDrainer) DrainReturns(result1 error) {
	fake.DrainStub = nil
	fake.drainReturns = struct {
		result1 error
	}{result1}
}

var _ syslog.Drainer = new(FakeDrainer)
